# Generated by Django 4.2.1 on 2024-01-29 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
