# Generated by Django 4.2.1 on 2024-02-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_conversation_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessages',
        ),
    ]
